ti = 1960; % 1960 for waccm, 1979 for ncep
tf = 2002;
l1 = 2.5;
l2 = 5;
nameflag = 1; % 1 is for pressure levels
dataflag = 2; % 1 is for NCEP, 2 is for WACCM
%fpath = '/net/fusi/raid01/mc1/WACCM3/SC_4x/run/wa3_SC.cam2.h0';
fpath = '/net/fusi/raid02/rls/Taiwan/WACCM3_SC_4x/run/wa3_SC.cam2.h0.';
%fpath = '/home/hermes_rd2/cdlib/ncep/Reanalysis2/Derived/pressure/hgt.mon.mean.nc';
nlevels = 2; % 0 is for one level, 1 is for two levels
latflag = 1; % 0 does not remove certain latitudes, 1 does
lat_h = 90;
lat_l = -90;
deseasonalizeflag = 1; % 0 does not deseasonalize, 1 does
detrendflag = 1; % 0 does not detrend, 1 does
order = 1; % order of the polynomial used for detrending
freq = 1/15; % frequency for the filter
filterflag = 1; % 0 does not filter, 1 does
scaleflag = 1; % 0 does not scale by sqrt(cos(lat)), 1 does
nEOF = 10; % number of EOFs desired
writeflag = 0; % 0 does not save EOFs, 1 does
nEOFwrt = 10; % this determines the number of EOFs to save, must be less than nEOF
